App/Controllers/SystemController.cs
// Copyright © Naked Objects Group Ltd ( http://www.nakedobjects.net). 
// All Rights Reserved. This code released under the terms of the 
// Microsoft Public License (MS-PL) ( http://opensource.org/licenses/ms-pl.html) 
using System.Web.Mvc;
using NakedObjects.Web.Mvc.Controllers;
using NakedObjects.Web.Mvc.Models;

namespace Simple.Controllers {

    //[Authorize]
    public class SystemController : SystemControllerImpl {


        public override ActionResult Root() {
            return base.Root();
        }
        
        public override ActionResult Index() {
            return base.Index();
        }

        public override ActionResult AboutNakedObjects() {
            return base.AboutNakedObjects();
        }

        public override ActionResult ChangeLicence() {
            return base.ChangeLicence();
        }

        public override ActionResult LogOut() {
            return base.LogOut();
        }

        public override ActionResult Quit() {
            return base.Quit();
        }

        public override ActionResult ExecuteFixture(string name) {
            return base.ExecuteFixture(name);
        }

        [HttpPost]
        public override ActionResult ClearHistory(bool clearAll) {
            return base.ClearHistory(clearAll);
        }

        [HttpPost]
        public override ActionResult ClearHistoryItem(string id, string nextId, ObjectAndControlData controlData) {
            return base.ClearHistoryItem(id, nextId, controlData);
        }

        [HttpPost]
        public override ActionResult ClearHistoryOthers(string id, ObjectAndControlData controlData) {
            return base.ClearHistoryOthers(id, controlData);
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext) {
            if (Request.Browser.Type.ToUpper() == "IE6" || Request.Browser.Type.ToUpper() == "IE7") {
                filterContext.Result = View("BrowserError");
                return;
            }

            base.OnActionExecuting(filterContext);
        }
    }
}

App/Views/Shared/ActionDialog.cshtml
@model NakedObjects.Web.Mvc.Models.FindViewModel
@using NakedObjects.Web.Mvc.Html

@{  
    Layout = "Site.WithServices.cshtml";
}

@section Title {@(Model.ContextAction.Name)}

@section MainContent { 
@(Html.TabbedHistory())   
    <div class="@(IdHelper.ActionDialogName)" id="@(Html.ObjectActionDialogId(Model.ContextObject, Model.ContextAction))" >
        @{ Html.RenderPartial("DialogControl", Model);}

    </div> 
}

App/Views/Shared/BrowserError.cshtml
@model dynamic
@using NakedObjects.Resources

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>@(MvcUi.BrowserErrorTitle)</title>
</head>
<body>
    <div class="error">
        <img alt="error" src="@(Url.Content("~/Images/system-error.png"))" />
        <p>@(MvcUi.BrowserErrorText)</p>
    </div>
</body>
</html>

App/Views/Shared/ConcurrencyError.cshtml
@model NakedObjects.Architecture.Persist.ConcurrencyException
@using NakedObjects.Web.Mvc.Html

@{ 
 ViewBag.Title = "@(NakedObjects.Resources.MvcUi.ConcurrencyErrorTitle)"; 
}

@section MainContent { 
@(Html.TabbedHistory())   
    <div class="error">
        <img alt="error"  src="@(Url.Content("~/Images/concurrency-error.png"))"/>
	    <h2>@(NakedObjects.Resources.MvcUi.ConcurrencyErrorTitle)</h2>

	    <p>@(Model.Message)</p>

        @if (Model.SourceNakedObject != null) {
            <h3>@(NakedObjects.Resources.MvcUi.ConcurrencyErrorObject):</h3>
            @(Html.Object(Html.ObjectTitle(Model.SourceNakedObject.Object).ToString(), IdHelper.ViewAction, Model.SourceNakedObject.Object))
        }
    </div> 
}

App/Views/Shared/DataUpdateError.cshtml
@model NakedObjects.Architecture.Persist.DataUpdateException
@using NakedObjects.Web.Mvc.Html

@{ 
 ViewBag.Title = "@(NakedObjects.Resources.MvcUi.DataUpdateErrorTitle)"; 
}

@section MainContent { 
@(Html.TabbedHistory())   
    <div class="error">
        <img alt="error"  src="@(Url.Content("~/Images/system-error.png"))" />
	    <h2>@(NakedObjects.Resources.MvcUi.DataUpdateErrorTitle)</h2>

	    <p>@(Model.Message)</p>
    </div> 
}

App/Views/Shared/DestroyedError.cshtml
@using NakedObjects.Resources
@using NakedObjects.Web.Mvc.Html

@{ 
 ViewBag.Title = "@(MvcUi.DestroyedErrorTitle)"; 
}

@section MainContent { 
@(Html.TabbedHistory())   
    <div class="error">
        <img alt="error"  src="@(Url.Content("~/Images/system-error.png"))" />
        <h2>
            @(MvcUi.DestroyedErrorText)
        </h2>
    </div> 
}

App/Views/Shared/FormWithFinderDialog.cshtml
@model NakedObjects.Web.Mvc.Models.FindViewModel
@using NakedObjects.Web.Mvc.Html
@using NakedObjects.Web.Mvc.Models


@if (Model.ViewType == FindViewModel.ViewTypes.Dialog) {
        ViewBag.Title =  Model.ContextAction.Name;
     } else {
         ViewBag.Title = Html.ObjectTitle(Model.ContextObject);
     }; 

@section MainContent { 
@(Html.TabbedHistory())   
    <div class="@(IdHelper.FindDialogName)">
        @if (Model.ViewType == FindViewModel.ViewTypes.Dialog) {        
            <div class="@(IdHelper.ActionDialogName)" id="@(Html.ObjectActionDialogId(Model.ContextObject, Model.ContextAction))">
                @{ Html.RenderPartial("DialogControl", Model);}
  
            </div>   
        } else {
            <div class="@(Html.ObjectEditClass(Model.ContextObject))" id="@(Html.ObjectTypeAsCssId(Model.ContextObject))">
                @{ Html.RenderPartial("ObjectEditControl", Model);}           
            </div>   
        }
    </div> 
}

App/Views/Shared/LogOnUserControl.cshtml
@* To use Razor views, see Naked Objects Manual (search for 'Razor') *@

@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "Login", "Account") ]
}

App/Views/Shared/ObjectEditControl.cshtml
@model object
@using NakedObjects.Resources
@using NakedObjects.Web.Mvc.Html
@using NakedObjects.Web.Mvc.Models
@using NakedObjects.Util

    @if (Model is FindViewModel) {
        var fvm = (FindViewModel) Model;

@*      @Html.Object(Html.ObjectTitle(fvm.ContextObject).ToString(), IdHelper.ViewAction, fvm.ContextObject) *@
        @Html.ValidationSummary(true, MvcUi.EditError)
        @Html.UserMessages()
        using (Html.BeginForm(IdHelper.EditAction,
                                Html.TypeName(fvm.ContextObject).ToString(),
                                new {id = Html.GetObjectId(fvm.ContextObject).ToString()},
                                FormMethod.Post,
                                new {@class = IdHelper.EditName})) {
            @(Html.PropertyListEdit(fvm.ContextObject, fvm.TargetObject, fvm.TargetAction, fvm.PropertyName, fvm.ActionResult))   
            }
     }else {     
        <div class="transient">UNSAVED - @(NameUtils.NaturalName(Html.TypeName().ToString()))</div>
        @(Html.ValidationSummary(true, MvcUi.EditError))
        @(Html.UserMessages())
        using (Html.BeginForm(IdHelper.EditAction,
                                Html.TypeName(Model).ToString(),
                                new {id = Html.GetObjectId(Model).ToString()},
                                FormMethod.Post,
                                new {@class = IdHelper.EditName})) {
            @(Html.PropertyListEdit(Model))     
            }
            
     } 
     @(Html.CancelButton(Model))  

App/Views/Shared/ObjectView.cshtml
@model System.Object
@using NakedObjects.Resources
@using NakedObjects.Web.Mvc.Html

@{
    
    Layout = "Site.WithServices.cshtml";
}

@section title {@Html.ObjectTitle(Model)}
@section MainContent { 
@(Html.TabbedHistory(Model))   
    <div class="@(Html.ObjectViewClass(Model))" id="@(Html.ObjectTypeAsCssId(Model))">
@*        @(Html.Object(Model))*@
        @(Html.UserMessages())

        @if (Html.ObjectIsNotPersistent(Model)) {
            using (Html.BeginForm(IdHelper.EditObjectAction,
                            Html.TypeName(Model).ToString(),
                            new {id = Html.GetObjectId(Model).ToString()},
                            FormMethod.Post,
                            new {@class = IdHelper.EditName})) {
            @(Html.MenuOnTransient(Model))
            if (Html.ObjectHasVisibleFields(Model)) {
                @(Html.PropertyList(Model))   
            }  
         }
        } else {
            @(Html.Menu(Model))
            if (Html.ObjectHasVisibleFields(Model)) {
                @(Html.PropertyList(Model))   
            }
        }
    </div> 
}

App/Views/Shared/PropertyEdit.cshtml
@using NakedObjects.Web.Mvc.Html
@using NakedObjects.Web.Mvc.Models

@if (Model is PropertyViewModel) {
    var pvm = Model as PropertyViewModel;

    @(Html.PropertyListEditWith(pvm.ContextObject, pvm.PropertyName))
} else {
    var fvm = Model as FindViewModel;

    if (fvm.ContextAction == null) {
        @(Html.PropertyListEditWith(fvm.ContextObject, fvm.TargetObject, fvm.TargetAction, fvm.PropertyName, fvm.ActionResult))
    } else {
        @(Html.ParameterListWith(fvm.ContextObject, fvm.TargetObject, fvm.ContextAction, fvm.TargetAction, fvm.PropertyName, fvm.ActionResult))
    }
}

App/Views/Shared/PropertyView.cshtml
@model NakedObjects.Web.Mvc.Models.PropertyViewModel
@using NakedObjects.Web.Mvc.Html

@(Html.PropertyListWith(Model.ContextObject, Model.PropertyName))

App/Views/Shared/ViewModel.cshtml
@using NakedObjects.Resources
@using NakedObjects.Web.Mvc.Html

@*This view is used, by default, for an object that implements IViewModelEdit,
    or that implements IViewModelSwitchable when it is in edit mode.  Otherwise
    viewmodels are rendered like any other objects using the ObjectView view. The use of
    this view for editable viewmodels is to avoid the rendering of a Save button.*@

@{ 
 ViewBag.Title = "@(Html.ObjectTitle(Model)" + "Edit View Model"; 
}
@section MainContent { 
@(Html.TabbedHistory(Model))   
    <div class="@(Html.ViewModelClass(Model))" id="@(Html.ObjectTypeAsCssId(Model))">
            @(Html.ObjectTitle(Model))
            @(Html.ValidationSummary(true, MvcUi.EditError))
            @(Html.UserMessages())
            @using (Html.BeginForm(IdHelper.EditAction,
                                      Html.TypeName(Model).ToString(),
                                      new {id = Html.GetObjectId(Model).ToString()},
                                      FormMethod.Post,
                                      new {@class = IdHelper.EditName})) {
                @(Html.PropertyListEdit(Model)) 
                @(Html.MenuOnTransient(Model))    
            }
    </div> 
}

App/Views/Shared/site.cshtml
<!DOCTYPE html>
<html lang="en">
    <head runat="server">
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="@(Url.Content("~/favicon.ico"))" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @(Styles.Render("~/Content/css"))
        @(Scripts.Render("~/bundles/modernizr"))
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">Naked Objects MVC - Razor</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @(Html.Partial("_LoginPartial"))
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@(Html.ActionLink("Home", "Index", "System"))</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("FeaturedContent", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderSection("MainContent", required: false)
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @(DateTime.Now.Year) - Naked Objects Group Ltd</p>
                </div>
            </div>
        </footer>

        @(Scripts.Render("~/bundles/jquery"))
        @RenderSection("ScriptsSection", required: false)
    </body>
</html>

App/Views/Shared/site.withservices.nologin.nobundle.cshtml
@using NakedObjects.Web.Mvc.Html
<!DOCTYPE html>
<html lang="en">
    <head runat="server">
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="@(Url.Content("~/favicon.ico"))" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @(Styles.Render("~/Content/nakedobjectscss" ))
        <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/smoothness/jquery-ui.css" rel="Stylesheet" />
        <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.0.6-development-only.js"></script>
    </head>
    <body>
        <header>
            @if (!Html.ViewContext.HttpContext.Request.IsAjaxRequest()) {    
                <div class="content-wrapper">
                    <div class="float-left">
                        <p class="site-title">@(Html.ActionLink("Naked Objects Group Ltd", "Index", "System"))</p>
                    </div>
                    <div class="float-right">
                        <section id="login">
                            Hello, <span class="username">@(Page.User.Identity.Name)</span>!
                        </section>
                        <nav>
                            <ul id="menu">
                                <li>@(Html.ActionLink("Home", "Index", "System"))</li>
                            </ul>
                        </nav>
                    </div>
                    @(Html.Services())
                </div>
            }
        </header>
        <div id="body">
            @RenderSection("FeaturedContent", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderSection("MainContent", required: false)
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @(DateTime.Now.Year) -  Naked Objects Group Ltd</p>
                </div>
            </div>
        </footer>

        <!--AJAX:  Replace nakedobjectsajax with nakedobjectsbasic bundle if non-ajax is required -->
        <!--DATE FORMATS:   The jquerydatepicker bundle specifies that the JQuery DatePicker uses the en-GB date format (dd/mm/yy).
        To use the US format (mm/dd/yy) just remove the bundle. Or to use another locale, specify the appropriate
        version of jquery.ui.datepicker in the bundle config -->
        
        <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.js"></script>
        <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.20/jquery-ui.js"></script>
        <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"></script>
        <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.js"></script>
        <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.validate.unobtrusive.js"></script>
   
        @(Scripts.Render( "~/bundles/nakedobjectsajax", "~/bundles/jquerydatepicker"))       
        @RenderSection("ScriptsSection", required: false)
    </body>
</html>